### ISSUE TITLE
Taxonomies command not working with multiple codenames

### ISSUE THREAD

**Issue by mberry1989** [Kontent-ai-consulting/kontent-ai-model-accelerator#1]
### Brief bug description

The comma delimiter in the --taxonomies command does not work. Console displays:
`[Warning][persona product_type]: Could not find taxonomy with given codename`

### Repro steps:

Command run:
_kda --action=remoteImport --environmentId=<envIdOmittedFromIssue> --apiKey=<apiKeyOmittedFromIssue --project=basic_product --taxonomies=persona, product_type_  

### Expected behavior

The two taxonomies from the basic_product should be imported from the master project to the target environment.

**Comment by Enngage** [comment]
Not sure why this happened, but I'm not able to reproduce it and it seems to work ok for me when using this command :

```bash
--action=remoteImport --environmentId=y --apiKey=x --model=basic_product --taxonomies=persona,product_type
```
