### ISSUE TITLE
Export command fails with Error: taxonomiesRaw.trim is not a function

### ISSUE THREAD

**Issue by mberry1989** [Kontent-ai-consulting/kontent-ai-model-accelerator#10]
### Brief bug description

When creating a new export.json file for advanced product, the accelerator CLI command fails with: Error: taxonomiesRaw.trim is not a function .

### Repro steps

Command used:

`npx @kontent-ai-consulting/content-model-accelerator --action=export -environmentId=<redacted_for_GH_Issue> --apiKey=<redacted_for_GH_Issue> --filename=product-model-advanced.json`

### Expected behavior

Command finishes without error.

### Additional context

The method in the error is found at: https://github.com/Kontent-ai-consulting/kontent-ai-model-accelerator/blob/08ed4f38785a9beac3717134f688cc4388395d64/lib/node/cli/app.ts#L289

Contact @mberry1989 for the source project ID and MAPI key, if needed.

**Comment by Enngage** [comment]
Fixed by https://github.com/Kontent-ai-consulting/kontent-ai-model-accelerator/commit/e3b75822d47564b9b4858cd335b7a4105ee73e69
