### ISSUE TITLE
Importing content types that contain existing snippets fails

### ISSUE THREAD

**Issue by mberry1989** [Kontent-ai-consulting/kontent-ai-model-accelerator#2]
### Brief bug description

Replacing an existing content type with an Accelerator that has the same codename fails if it contains a content type snippet. Full cmd debug attached.

cmd used:
`kda --action=remoteImport --environmentId=<envIdOmittedFromIssue> --apiKey=<apiKeyOmittedFromIssue> --project=basic_organization`

### Repro steps

1. Go to a project containing an already imported "Organization" content type
2. Delete the existing content type
3. Use the remoteImport cmd to import the basic_organization Accelerator from the master project to the target project
4. See attached error

### Expected behavior

The import will ignore the metadata snippet, provide a message, and import successfully (similar to other pre-existing elements).

### Debug:

[debug-log-failed-due-to-snippet.txt](https://github.com/Enngage/kontent-ai-model-accelerator/files/14068765/debug-log-failed-due-to-snippet.txt)

**Comment by Enngage** [comment]
I've updated the import to process to import models even if object with the same codename exists in target project. The accelerator will simply auto-generate suffix to codename to make sure it's unique.
