### ISSUE TITLE
README feedback

### ISSUE THREAD

**Issue by mberry1989** [Kontent-ai-consulting/kontent-ai-model-accelerator#4]
### Motivation

The Execution section with commands confused some of my testers and required re-reading the README or using the `kda --help` command to understand.

### Proposed solution

A diagram & summary of how the tool works behind the scenes could help users understand what the tool is for and how to leverage it. Each action should contain some summary/description and a practical example.

### Additional comment
When we get final approval for naming, `kda` as an action command should likely be replaced.

**Comment by mberry1989** [comment]
_Content Model Accelerators_, _Accelerator Gallery_, and _Accelerators_ will be the terms we used in this project.

I'm proposing the package name: 
@kontent-ai/content-model-accelerators

and command names:
kma (Kontent.ai model accelerators) or kag (Kontent.ai accelerator gallery) 

to stick with the package name and "3-letter" cmd convention you've implemented in other tools.

**Comment by Enngage** [comment]
I've updated Readme to make it a bit clearer (and nicer). Feel free to change anything you want in the readme though. 

As for the package name I'm ok with what you proposed, but I would use a singular:

`@kontent-ai/content-model-accelerator`

As the tool itself is a singular tool and it makes a bit more sense to me :)
