### ISSUE TITLE
Add confirmation dialogue prior to executing imports/exports

### ISSUE THREAD

**Issue by mberry1989** [Kontent-ai-consulting/kontent-ai-model-accelerator#5]
### Motivation

Users may need to consider what is about to be imported before executing a remote import.

### Proposed solution

Raise a dialogue in the terminal that contains a readout of: 

1. what is about to be imported
2. what the name of the accelerator is
3. what the name of the target environment is
4. a final "Y/N" confirmation that kicks off the import process

### Additional context

The feature was originally requested by Jan Cerman.

**Comment by Enngage** [comment]
I've added confirmation prompt (y/n) with target project / environment info to confirm the selection
