### ISSUE TITLE
Validation error thrown when using the --taxonomies flag

### ISSUE THREAD

**Issue by mberry1989** [Kontent-ai-consulting/kontent-ai-model-accelerator#8]
### Brief bug description

When using the command:

`kontent-ai-accelerator --action=remoteImport --environmentId=<removedForIssue> --apiKey=<removedForIssue> --model=advanced_product --taxonomies=persona`

error:
`Error:  The provided request body is invalid. See 'validation_errors' for more information and specify a valid JSON object. The referenced taxonomy group '{external id: b84ac429-274c-428d-ab8f-86f039664e4c}' was not found. Provide a reference to an existing taxonomy group.`

The accelerator fails with a validation error as a taxonomy that is referenced within the "advanced_product" model is excluded due to the --taxonomies specification.

### Repro steps

1. Run `kontent-ai-accelerator --action=remoteImport --environmentId=<removedForIssue> --apiKey=<removedForIssue> --model=advanced_product --taxonomies=persona`

### Expected behavior

The taxonomies flag should import only the targetted taxonomy group, and not attempt to import the content types that reference it, to avoid reference errors.

**Comment by Enngage** [comment]
I've updated this so that when you specify any object (taxonomy, snippet, content type) only that specific object gets imported (e.g. if you specify 1 taxonomy, only that taxonomy gets imported as types and snippets get omitted).
